<?php

namespace Eccube\Repository;

use Eccube\Entity\Customer;
use Eccube\Entity\PointHistory;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * PointHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointHistoryRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, PointHistory::class);
    }
    
    public function getCurrentPoint(\Eccube\Entity\Customer $Customer){
        $result = $this->createQueryBuilder('p')
        ->select('SUM(p.point) AS total')
        ->where('p.Customer = :Customer')
        ->setParameter('Customer', $Customer)
        ->getQuery()
        ->getSingleResult();
        
        return $result['total'];
    }
}
